
        // SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)"
        //
        // THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

        
            #[path = "minimal.skel.rs"]
            mod minimal_skel;
            
            pub use minimal_skel::*;
            