// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)"
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

#[path = "bootstrap.skel.rs"]
mod bootstrap_skel;

#[path = "minimal.skel.rs"]
mod minimal_skel;

#[path = "kprobe.skel.rs"]
mod kprobe_skel;

#[path = "xdp.skel.rs"]
mod xdp_skel;

#[path = "minimal_legacy.skel.rs"]
mod minimal_legacy_skel;

#[path = "fentry.skel.rs"]
mod fentry_skel;

pub use bootstrap_skel::*;

pub use minimal_skel::*;

pub use kprobe_skel::*;

pub use xdp_skel::*;

pub use minimal_legacy_skel::*;

pub use fentry_skel::*;
